txt=input("digite ou cole um texto base aqui >> ")
print(f'o texto tem {len(txt.strip())} caracteres contando os espaços')
print(f'texto base: {txt}')
substring = input('\no que deseja procurar? ')
print(f'temos {txt.lower().count(substring)}  "{substring}"  no texto  ')
